"""Remove rollout_id from environment, add env_id to rollout, remove unique constraint from rollout.rollout_id

Revision ID: e3988accc2ef
Revises: 7bd65e048510
Create Date: 2025-12-31 14:34:07.124439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3988accc2ef'
down_revision: Union[str, Sequence[str], None] = '7bd65e048510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Drop the old foreign key and index from environment.rollout_id
    # Note: If tables were created directly from models (e.g., via rebuild_database.py),
    # these indexes/constraints may not exist, so we use IF EXISTS where possible
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Check if index exists before dropping
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes('environment')]
        if 'ix_environment_rollout_id' in indexes:
            op.drop_index(op.f('ix_environment_rollout_id'), table_name='environment')
    except Exception:
        # Index doesn't exist, skip
        pass
    
    # Check if foreign key constraint exists before dropping
    try:
        foreign_keys = inspector.get_foreign_keys('environment')
        fk_names = [fk['name'] for fk in foreign_keys if fk['name'] and 'rollout_id' in fk.get('constrained_columns', [])]
        if fk_names:
            op.drop_constraint(fk_names[0], 'environment', type_='foreignkey')
    except Exception:
        # Constraint doesn't exist, skip
        pass
    
    # Step 2: Add env_id to rollout as nullable first
    op.add_column('rollout', sa.Column('env_id', sa.Integer(), nullable=True))
    
    # Step 3: For each existing rollout, create an environment record and link them
    # This handles data migration
    connection = op.get_bind()
    rollouts = connection.execute(sa.text("SELECT id, rollout_id FROM rollout WHERE env_id IS NULL"))
    
    for rollout_row in rollouts:
        rollout_id = rollout_row[0]
        rollout_id_str = rollout_row[1]
        
        # Create environment record (we don't have box_id yet, it will be updated later)
        connection.execute(
            sa.text("""
                INSERT INTO environment (env_type, status, box_type, created_at, updated_at)
                VALUES ('android', 'pending', 'android', NOW(), NOW())
                RETURNING id
            """)
        )
        env_result = connection.execute(sa.text("SELECT id FROM environment ORDER BY id DESC LIMIT 1"))
        env_id = env_result.fetchone()[0]
        
        # Update rollout with env_id
        connection.execute(
            sa.text("UPDATE rollout SET env_id = :env_id WHERE id = :rollout_id"),
            {"env_id": env_id, "rollout_id": rollout_id}
        )
    
    # Step 4: Now make env_id NOT NULL
    op.alter_column('rollout', 'env_id', nullable=False)
    
    # Step 5: Remove rollout_id from environment
    op.drop_column('environment', 'rollout_id')
    
    # Step 6: Update rollout.rollout_id index to remove unique constraint
    op.drop_index(op.f('ix_rollout_rollout_id'), table_name='rollout')
    op.create_index(op.f('ix_rollout_rollout_id'), 'rollout', ['rollout_id'], unique=False)
    
    # Step 7: Create index and foreign key for rollout.env_id
    op.create_index(op.f('ix_rollout_env_id'), 'rollout', ['env_id'], unique=False)
    op.create_foreign_key(None, 'rollout', 'environment', ['env_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rollout', type_='foreignkey')
    op.drop_index(op.f('ix_rollout_env_id'), table_name='rollout')
    op.drop_index(op.f('ix_rollout_rollout_id'), table_name='rollout')
    op.create_index(op.f('ix_rollout_rollout_id'), 'rollout', ['rollout_id'], unique=True)
    op.drop_column('rollout', 'env_id')
    op.add_column('environment', sa.Column('rollout_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('environment_rollout_id_fkey'), 'environment', 'rollout', ['rollout_id'], ['id'])
    op.create_index(op.f('ix_environment_rollout_id'), 'environment', ['rollout_id'], unique=False)
    # ### end Alembic commands ###
